kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: amazoncorretto:8
    volumes:
      - name: deps
        path: /root/.m2
    commands:
      - ./gradlew test

  - name: build
    image: amazoncorretto:8
    volumes:
      - name: deps
        path: /root/.m2
    commands:
      - ./gradlew --no-daemon build -x test

  - name: release
    image: node:13
    commands:
      - npx semantic-release
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event:
        exclude:
        - tag

volumes:
  - name: deps
    temp: {}
