coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "**/src/test/"
  - "**/src/testFixtures"